### ISSUE TITLE
Drop twitter's util-collection

### ISSUE THREAD

**Issue by tkrs** [yanana/uap-scala#14]
Twitter util deleted `util-collection` in [19.2.0](https://github.com/twitter/util/blob/a42b56d8c70c7eca68f1ba06619d538720abc5b6/CHANGELOG.rst#breaking-api-changes-6), so `LruMap` has been deleted at the same time. We have to consider what to do with [`ChachingParser`](https://github.com/yanana/uap-scala/blob/08e78193871d2977c20070cf9cbf246b3e2f7075/src/main/scala/ua/parser/CachingParser.scala). I think it's okay to delete it, what do you think about it? @yanana

**Comment by yanana** [comment]
@tkrs Thanks for your opinion! I quite agree with you. We can add the feature when it's needed using guava or something.
